/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as savingPoolSol from "./SavingPool.sol";
export type { savingPoolSol };
export type { CreditScore } from "./CreditScore";
export type { EmergencyPool } from "./EmergencyPool";
export type { InsurancePool } from "./InsurancePool";
export type { MockERC20 } from "./MockERC20";
export type { Reputation } from "./Reputation";
